CREATE DATABASE GroupProject;

GO

USE GroupProject;

CREATE TABLE [User]
(
	Id INT PRIMARY KEY IDENTITY,
	FirstName NVARCHAR(100) NOT NULL,
	Surname NVARCHAR(100) NOT NULL,
	Patronym NVARCHAR(100) NULL,
	Username NVARCHAR(100) NOT NULL,
	[Password] NVARCHAR(100) NOT NULL,
	CONSTRAINT UQ_Username UNIQUE(Username)
);